spring.application.name=BarberRecods

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.admin.username=${APP_ADMIN_USERNAME}
app.admin.password=${APP_ADMIN_PASSWORD}

app.working-hours.start=09:00
app.working-hours.end=20:00
app.slot-interval-minutes=30
app.timezone=Europe/Moscow

app.backups.path=/app/backups

server.port=8080
spring.jackson.time-zone=Europe/Moscow
